version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    devices:
      - nvidia.com/gpu=all
    security_opt:
      - label=disable

  agent:
    build: .
    container_name: llm-agent
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app

volumes:
  ollama-data:
